name: "Tests"
on:
  pull_request:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm run test

  usage:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        host: 'rc4-md5.badssl.com'
        grade: 'A'
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: testssl.sh reports
        path: 'output/'
